#!/bin/bash

#
# Backup in Docker container
#
# (C) 2017 Stefan Schallenberg
#
# Test script

##### Test Init ##############################################################
# Initialise tests including any necessary workaround
function test_init {

	if which "ip" >/dev/null ; then
		my_ip="$USER@$(set -o pipefail
			ip -4 -j a show dev docker0 primary |
			jq '.[].addr_info[0].local')" &&
		my_ip=${my_ip//\"}
		test_assert "$?" "Could not get IP with command ip" || return 1
	elif which "ipconfig" >/dev/null ; then
		my_ip="$USER@$(ipconfig getifaddr en0 en1)" &&
		test ! -z "$my_ip"
		test_assert "$?" "Could not get IP with command ipconfig" || return 1
	else
		my_ip=""
	fi

	if [[ "$OSTYPE" =~ darwin* ]] ; then
		printf "Activate MacOS workaround - using /usr/local/bin/rsync\n"
		rsync_opt="--rsync-path=/usr/local/bin/rsync"
	else
		rsync_opt=""
	fi

	return 0
}

##### Test Executer ##########################################################
# Parameters:
#     1 - command in custom backup shell
#     2 - expected RC [default: 0]
function test_exec_backupdocker {
	if [ "$#" -lt 1 ] ; then
		test_assert "1" "got %s parms (exp 1+)" >&2 || return 1
	fi
	rc_exp="$1"
	shift

	cat >$TESTSETDIR/backup/backup <<<"$@" &&
	chmod +x $TESTSETDIR/backup/backup </dev/null
	test_assert "$?" "Write backup script" >&2 || return 1

	local docker_cmd=""
	docker_cmd+="docker run"
	docker_cmd+=" -v $TESTSETDIR/backup:/backup"
	docker_cmd+=" -v ~/.ssh/id_rsa:/secrets/id_rsa:ro"
	docker_cmd+=" -e DEBUG=1"
	docker_cmd+=" nafets227/backup:test"
	docker_cmd+=" . /backup/backup"

	printf "test_exec_simple \"%s\" \"%s\" \"%s\"" \
		"$docker_cmd" \
		"$rc_exp" \
		"Backup Command $*"

	return $TESTRC
}

##### Test Build #############################################################
function test_build {

	# Compile / Build docker
	test_exec_simple \
		"docker build -t nafets227/backup:test $BASEDIR/.." \
		0

	[ $TESTRC -eq 0 ] || return 1

	return 0
}

##### Test: no custom script #################################################
function test_runempty {
	test_exec_simple \
		"docker run nafets227/backup:test" \
		1
	
	return $?
}

##### Main ###################################################################
BASEDIR=$(dirname $BASH_SOURCE)
. $BASEDIR/../util/test-functions.sh || exit 1
for f in $BASEDIR/*.sh ; do
	. $f || exit 1
done

testset_init || exit 1
if [ ! -d $TESTSETDIR/backup ] ; then
	mkdir $TESTSETDIR/backup || return 1
fi

if test_build && test_init ; then
	test_runempty
	test_rclone
	test_rclone_hist
	test_file
	test_file_hist
	test_imap
	test_imap_hist
fi

testset_summary
exit $?
