#!/bin/bash
#
# (C) 2015 Stefan Schallenberg
#

printf "starting ENTRYPOINT backup_main\n"

##### Parse Configs / Envirionment ###########################################
DEBUG=${DEBUG-0}
debug=$DEBUG

#Source all modules in install.d
for f in /usr/lib/backup/*.sh ; do
    echo "Loading Module $f"
    . $f
done

if [ x"$DEBUG" == x1 ] ; then
	set -x
fi

##### Now start the custom scipt
if [ $# -ge 1 ] ; then
	printf "executing custom command %s\n" "$*"
	"$@"
else
	printf "executing standard command backup/backup\n"
	. backup/backup
fi
