#!/usr/bin/env bash

#
# Backup in Docker container
#
# (C) 2017 Stefan Schallenberg
#
# Test script

##### Test Init ##############################################################
# Initialise tests including any necessary workaround
function test_init {

	my_fileopt=""

	if 	[[ "$OSTYPE" =~ darwin* ]] ; then
		my_ip="$USER@$(ipconfig getifaddr en0 en1)"
		my_fileopt="--macos"
		TEST_RSYNCOPT="--rsync-path=/opt/homebrew/bin/rsync"
	elif which "ip" >/dev/null ; then
		my_ip="$USER@$(set -o pipefail
			ip -4 -j a show dev docker0 primary |
			jq '.[].addr_info[0].local')"
		my_ip=${my_ip//\"}
		TEST_RSYNCOPT=""
	else
		my_ip=""
		test_expect_value "1" "0" \
			"Could not get IP (not on MacOS and command ip missing)"
		TEST_RSYNCOPT=""
	fi

	my_host="$HOSTNAME"
	: "$my_host" # make shellcheck happy

	return 0
}

##### Test chowner ###########################################################
# Parameters:
#     1 - test file to chown
function test_chown {
	if 	! [[ "$OSTYPE" =~ darwin* ]] ; then
		chown 41598:41598 "$1"
	fi

	return 0
}

##### Test Executer ##########################################################
# Parameters:
#     1 - command in custom backup shell
#     2 - expected RC [default: 0]
function test_exec_backupdocker {
	rc_exp="$1"
	shift

	if \
		! cat >"$TESTSET_DIR/backup/backup" <<<"$@" ||
		! chmod +x "$TESTSET_DIR/backup/backup"
	then
		printf "test_expect_value %s 0 \"%s\"\n" "$?" "Write backup script"
		return 1
	fi

	if ! cp ~/.ssh/id_ed25519 "$TESTSET_DIR/id_ed25519"
	then
		test_expect_value "$?" 0 "Copy SSH Key"
		return 1
	fi
	if 	! [[ "$OSTYPE" =~ darwin* ]] ; then
		if ! chown 41598:41598 "$TESTSET_DIR/id_ed25519" ; then
			test_expect_value "$?" 0 "chown SSH Key"
			return 1
		else
			test_expect_value 0 0 "not chowning SSH Key"
		fi
	else
		test_expect_value 0 0 "not chowning SSH Key"
	fi

	TEST_CALLDEPTH=1 \
	test_exec_cmd "$rc_exp" "Backup Command $*" \
		docker run \
			-v "$TESTSET_DIR/backup:/backup" \
			-v "$TESTSET_DIR/id_ed25519:/secrets/id_ed25519:ro" \
			-e DEBUG=1 \
			-e MAIL_TO \
			-e MAIL_FROM \
			-e MAIL_URL \
			-e MAIL_HOSTNAME \
			"$TESTIMG" \
			. /backup/backup

	return 0
}

##### Test: no custom script #################################################
function test_runempty {
	test_exec_cmd 1 "" \
		docker run "$TESTIMG"

	return $?
}

##### Test: Email alerting ###################################################
function test_email {
	local imappw imapurl smtppw smtpurl

	test_expect_vardefined \
		TESTALERTMAIL_ADR \
		TESTALERTMAIL_FROM \
		TESTALERTMAIL_URL \
		TESTALERTMAIL_USER \
		TESTALERTMAIL_SECRET \
		TESTALERTMAIL_IMAP_URL \
		TESTALERTMAIL_IMAP_SECRET
		# TESTALERTMAIL_HOSTNAME can be intendedly empty so dont check it

	imappw="$(cat "$TESTALERTMAIL_IMAP_SECRET")"
	imapurl="imap://${TESTALERTMAIL_ADR//@/%40}"
	imapurl+=":$($TEST_SNAIL -# <<<"urlcodec encode $imappw")"
	imapurl+="@$TESTALERTMAIL_IMAP_URL/INBOX"

	smtppw="$($TEST_SNAIL -# <<<"urlcodec encode $imappw")"
	smtpurl="smtp://${TESTALERTMAIL_USER//@/%40}:$smtppw@$TESTALERTMAIL_URL"

	test_cleanImap "$TESTALERTMAIL_ADR" "$imappw" "$TESTALERTMAIL_IMAP_URL"

	# Trigger Error Email with empty command and unset MAIL_SSL
	export MAIL_TO=$TESTALERTMAIL_ADR
	export MAIL_URL="$TESTALERTMAIL_URL"
	unset MAIL_SSL
	export MAIL_FROM="$TESTALERTMAIL_FROM"
	test_exec_backupdocker 0 ""

	sleep 10 # let mail be processed

	test_exec_recvmail "$imapurl" 0 "-S 'imap-use-starttls'"
	test_cleanImap "$TESTALERTMAIL_ADR" "$imappw" "$TESTALERTMAIL_IMAP_URL"

	# @TODO Trigger Error Email with MAIL_SSL=0

	# Trigger Error Email with empty command and send with STARTTLS
	export MAIL_TO=$TESTALERTMAIL_ADR
	export MAIL_URL="$smtpurl"
	export MAIL_SSL=1
	export MAIL_FROM="$TESTALERTMAIL_FROM"
	test_exec_backupdocker 0 ""

	sleep 10 # let mail be processed

	test_exec_recvmail "$imapurl" 0 "-S 'imap-use-starttls'"
	test_cleanImap "$TESTALERTMAIL_ADR" "$imappw" "$TESTALERTMAIL_IMAP_URL"

	# @TODO execute test succeeding and verify EMail sent
	#test_exec_backupdocker 0 \
	#	"backup file" \
	#	"$source" \
	#	"$dest" \
	#	"$@"
	#test_expect_filecount "backup/file/dest" 0
	#
	#sleep 10
	#
	#test_exec_recvmail "$mailimapurl" 0 "-S 'imap-use-starttls'"
	#test_cleanImap "$TESTALERTMAIL_ADR" "$imappw" "$TESTALERTMAIL_IMAP_URL"

	# @ TODO test MAIL_HOSTNAME

	unset MAIL_TO MAIL_URL MAIL_FROM # works even for exported vars

	return 0
}

##### Main ###################################################################
export LC_ALL=C # override any user-defined locale
set -Eeuo pipefail ; shopt -s inherit_errexit ; # improved err handling

BASEDIR=$(dirname "${BASH_SOURCE[0]}")

#shellcheck source-path=SCRIPTDIR/../util
. "$BASEDIR/../util/util_err_functions.sh"
. "$BASEDIR/../util/util_test_functions.sh"
. "$BASEDIR/config.sh"

testset_init "$@"

tests=() TESTIMG=""
for p in "${TESTSET_PARM[@]}" ; do
	case "$p" in
		all)
			tests=( base rclone file imap )
			;;
		base|rclone|file|imap)
			tests+=( "$p" )
			;;
		!base|!rclone|!file|!imap)
			tests=( "${tests[@]/"${p:1}"}" )
			;;
		*)
			TESTIMG="$p"
	esac
done

printf "Executing tests %s with image %s\n" \
	"${tests[*]}" "${TESTIMG:-<temporary image>}"

test_expect_value "$(( ${#tests[@]} > 0 ? 1 : 0 ))" 1 \
	"Nr of tests to be executed"
test_is_cmdavail curl offlineimap jq "$TEST_SNAIL"

if testset_issuccess ; then
	if [ ! -d "$TESTSET_DIR/backup" ] ; then
		mkdir "$TESTSET_DIR/backup"
	fi
	test_chown "$TESTSET_DIR/backup"
	if [ -z "$TESTIMG" ] ; then
		TESTIMG="nafets227/backup:test"
		test_exec_cmd 0 "Build temporary image" \
			docker build -t "$TESTIMG" "$BASEDIR/.."
	fi
	test_init
fi

if testset_issuccess ; then
	for t in "${tests[@]}" ; do
		case "$t" in
			base)
				test_runempty
				test_email
				;;
			rclone)
				unset MAIL_TO MAIL_URL # disable mailing for following tests
				. "$BASEDIR/test-rclone.sh"
				test_rclone2file
				test_rclone2file_hist
				test_file2rclone
				;;
			file)
				unset MAIL_TO MAIL_URL # disable mailing for following tests
				. "$BASEDIR/test-file-hist.sh"
				. "$BASEDIR/test-file.sh"
				test_file
				test_file_hist
				;;
			imap)
				unset MAIL_TO MAIL_URL # disable mailing for following tests
				. "$BASEDIR/test-imap-hist.sh"
				. "$BASEDIR/test-imap.sh"
				test_imap
				test_imap_hist
				;;
			*)
				test_expect_value 1 0 "Unknown test \"$t\""
		esac
	done
fi

testset_summary || exit 1

exit 0
