apiVersion: v2
name: nafets227-backup
description: Container based implementation of backup.
type: application
# editorconfig-checker-disable
# - version will be created based on branch etc and may get very long
# - no way to make URL shorter
version: 0.0.0 # will be replaced by CI
appVersion: "0.0.0" # will be replaced by CI
icon: https://raw.githubusercontent.com/nafets227/backup/master/docs/images/nafets227-backup-256.png
