# Default values for nafets227-backup.

nafets227Backup:
  schedule:
    cron: "0 0 * * *" # midnight every day
    # timeZone: "Europe/Berlin"
    activeDeadlineSeconds: 82800 # 23 hours

# This sets the container image
# more information can be found here:
# https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/nafets227/backup
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secrets for pulling an image from a private repository
# more information can be found here:
# editorconfig-checker-disable-next-line
# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout:
# https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# This is for setting Kubernetes Labels to a Pod.
# For more information checkout:
# https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - NET_RAW
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  # runas User must be the same as defined in the image
  # otherwise emailing will not work, since mailx (aka s-nail)
  # requires the user to be defined inside the image (/etc/passwd)
  runAsUser: 41598

  # If you need root to access to some files to be backed up, replace above
  # default settings with the following lines:
  #
  # allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #     - NET_RAW
  #     - ALL
  #   add:
  #     - DAC_READ_SEARCH
  #     - DAC_OVERRIDE
  #     - FOWNER
  #     - CHOWN
  # readOnlyRootFilesystem: true
  # runAsNonRoot: false
  # runAsUser: 0

resources: {}
  # If you do want to specify resources, uncomment the following lines,
  # adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
