#!/usr/bin/env bash
#
# Cleanup old GHCR prerelease versions.
#
# Keeps:
#   - stable releases (1.2.3)
#   - latest
#
# Deletes:
#   - prerelease versions older than KEEP_DAYS
#
# Examples:
#   1.2.4-dev.17
#   1.2.4-br-feature-login.5
#

export LC_ALL=C
set -Eeuo pipefail ; shopt -s inherit_errexit

KEEP_DAYS="${KEEP_DAYS:-30}"

PACKAGE="${1:?Usage: cleanup-ghcr <package-name>}"
OWNER="${GITHUB_REPOSITORY_OWNER:?}"

PACKAGE_ESCAPED="${PACKAGE//\//%2F}"
BASEURL="/users/${OWNER}/packages/container/${PACKAGE_ESCAPED}"

if date -u -d "-1 day" >/dev/null 2>&1; then
	# GNU date (Linux / GitHub runner)
	CUTOFF_DATE=$(date -u -d "-${KEEP_DAYS} days" +"%Y-%m-%dT%H:%M:%SZ")
else
	# BSD date (macOS)
	CUTOFF_DATE=$(date -u -v "-${KEEP_DAYS}d" +"%Y-%m-%dT%H:%M:%SZ")
fi

printf "Cleaning up package %s prereleases older than %s\n:" \
	"ghcr.io/${OWNER}/${PACKAGE}" "${CUTOFF_DATE}"

gh api --paginate "$BASEURL/versions" |
jq -r --arg cutoff "$CUTOFF_DATE" '
	.[]
	| select(.created_at < $cutoff)
	|
		{
			id: .id,
			created: .created_at,
			tags: (.metadata.container.tags // [])
		}
	| select(.tags | length > 0)
	|
		[
			.id,
			.created,
			(.tags | join(","))
		]
	| @tsv
' |
while IFS=$'\t' read -r ID CREATED TAGS
do
	DELETE=true

	IFS=',' read -ra TAG_ARRAY <<< "$TAGS"

	for TAG in "${TAG_ARRAY[@]}"
	do
		case "$TAG" in
			latest)
				DELETE=false
				;;

			# Stable SemVer release
			[0-9]*.[0-9]*.[0-9]*)
				if [[ "$TAG" != *-* ]]; then
					DELETE=false
				fi
				;;

			# Old releases with preceding "v"
			v[0-9.]*)
				if [[ "$TAG" != *-* ]]; then
					DELETE=false
				fi
				;;
		esac
	done

	if [[ "$DELETE" == true ]]; then
		printf "Deleting tag %s (id %s, created %s)\n" \
			"$TAGS" "$ID" "$CREATED"

		gh api \
			--method DELETE \
			"$BASEURL/versions/${ID}"
	else
		printf "Keeping tag %s\n" "$TAGS"
	fi

done
