#!/bin/bash
#
# (C) 2015 Stefan Schallenberg
#

##### Execute on different machine ###########################################
function backup_execremote {
	remotemachine="$1"
	shift

	scp -r $MODDIR/* $remotemachine:$REMOTE_MODDIR &&
	scp $BASH_SOURCE $remotemachine:$REMOTE_MODDIR/backup_main &&
	ssh $remotemachine <<-EOF &&
		DEBUG=$DEBUG
		$REMOTE_MODDIR/backup_main "$@"
		EOF
	/bin/true || return 1

	return 0
}

##### Notify on Backup result and Deleted files via Email ####################
function backup_notify {
	# Options:
	#	--deleted List deleted files on remote system
	# Parms
	# 	1 - Sender Email adress, e.g. "my name <no-reply@example.org"
	#	2 - Recipient Email adress

	return 0
	# Old implementation as base follow
	###################################

	#if [ -s $LDIR/crypt.filestodelete ] ; then
	#printf "Sending EMail with list of deleted files.\n"
	#(
	#    printf "%s finished at %s\n\n" "$0" "$(date +"%Y-%m-%d %H:%M:%S")"
	#
	#    backup_rsync_print \
	#        $LDIR/crypt.filestodelete \
	#        "/srv/backup/data.crypt" \
	#        "remotebackup@stevro.dyndns.eu:/crypt"
	#
	#) 2>&1 </dev/null | mail \
	#    -r "nafets-backup-upload <no-reply@nafets.dyndns.eu>" \
	#    -s "Deleted files found" \
	#    infos@nafets.de
	#
	#else
	#    printf "No deleted Files. Not sending EMail.\n"
	#fi
	#
	#if [ -s $LDIR/euserv.fotos.filestodelete ] ||
	#   [ -s $LDIR/euserv.music.filestodelete ] ; then
	#printf "Sending EMail with list of deleted files.\n"
	#(
	#    printf "%s finished at %s\n\n" "$0" "$(date +"%Y-%m-%d %H:%M:%S")"
	#
	#    backup_rsync_print \
	#        $LDIR/euserv.fotos.filestodelete \
	#        "/srv/samba/data/fotos" \
	#        "remotebackup@stevro.dyndns.eu:/fotos"
	#
	#    backup_rsync_print \
	#        $LDIR/euserv.music.filestodelete \
	#        "/srv/samba/data/music" \
	#        "remotebackup@stevro.dyndns.eu:/music"
	#
	#) 2>&1 </dev/null | mail \
	#    -S smtp=smtp://mail.intranet.nafets.de \
	#    -S hostname=$HOSTNAME.dom.nafets.de \
	#    -r "nafets-backup-upload-euserv <no-reply@nafets.dyndns.eu>" \
	#    -s "Deleted files found" \
	#    infos@nafets.de
	#
	#else
	#    printf "No deleted Files. Not sending EMail.\n"
	#fi
	#}
}

##### Main ###################################################################
printf "starting ENTRYPOINT backup_main\n"
readonly MODDIR=/usr/lib/nafets227.backup
readonly REMOTE_MODDIR=/usr/local/lib/nafets227.backup

##### Parse Configs / Envirionment ###########################################
DEBUG=${DEBUG-0}
debug=$DEBUG

#Source all modules in install.d
for f in $MODDIR/*.sh ; do
    echo "Loading Module $f"
    . $f
    if [ x$? != x0 ] ; then
	    printf "Error loading module %s\n" "$f"
	    exit 1
    fi
done

if [ x"$DEBUG" == x1 ] ; then
	set -x
fi

##### Now start the custom scipt
if [ $# -ge 1 ] ; then
	printf "executing custom command %s\n" "$*"
	"$@"
else
	printf "executing standard command backup/backup\n"
	. backup/backup
fi

exit $?
