#!/bin/bash
#
# (C) 2015 Stefan Schallenberg
#

##### Execute on different machine ###########################################
function backup_remote {
	[ "$#" -lt 8 ] && return 1

	local remotemachine="$1"
	local remotesecret="$2"
	local bck_type="$3"
	local bck_src="$4"
	local bck_dst="$5"
	local bck_src_secret="$6"
	local bck_dst_secret="$7"
	local bck_histdate="$8"
	shift 8

	if [ -z "$remotemachine" ] ||
	   [ -z "$remotesecret" ] ; then
		return 1
	fi

	#----- remove remotemachine from URL ---------------------------------
	bck_src="${bck_src##$remotemachine:}"
	bck_dst="${bck_dst##$remotemachine:}"

	#----- set hist parm if present ------
	local rem_hist=""
	if [ ! -z "$bck_histdate" ] ; then
		rem_hist="--histraw \"$bck_histdate\""
	fi

	local rc
	printf "===== Start Executing on %s =====\n" "$remotemachine"
	ssh -o StrictHostKeyChecking=no $remotemachine -i $remotesecret<<-EOF &&
		[[ x"$DEBUG" == x1 ]] && set -x
		mkdir -p $REMOTE_MODDIR
		EOF
	scp -o StrictHostKeyChecking=no -i $remotesecret \
		-r "$(dirname "$0")"/*.sh $remotemachine:$REMOTE_MODDIR &&
	{
		if [ -z "$bck_src_secret" ] ; then
			true
		else
			scp -o StrictHostKeyChecking=no -i $remotesecret \
				$bck_src_secret \
				$remotemachine:$REMOTE_MODDIR/srcsecret &&
			bck_src_secret="--srcsecret $REMOTE_MODDIR/srcsecret"
		fi
	} &&
	{
		if [ -z "$bck_dst_secret" ] ; then
			true
		else
			scp -o StrictHostKeyChecking=no -i $remotesecret \
				$bck_dst_secret \
				$remotemachine:$REMOTE_MODDIR/dstsecret &&
			bck_dst_secret="--dstsecret $REMOTE_MODDIR/dstsecret"
		fi
	} &&
	ssh -o StrictHostKeyChecking=no $remotemachine -i $remotesecret<<-EOF
		[[ x"$DEBUG" == x1 ]] && set -x
		export DEBUG=$DEBUG
		# please note the trick to have a correct quoting on the
		# destination machine. Simply using \"\$@\" does not work.
		$REMOTE_MODDIR/backup_main backup --local \
			"$bck_type" \
			"$bck_src" \
			"$bck_dst" \
			$bck_src_secret \
			$bck_dst_secret \
			$rem_hist \
			$(
			for s in "$@" ; do
				printf " \"%s\"" "$s"
			done
			)
		exit \$?
		EOF
	rc=$?
	printf "===== Returning with RC=%d from %s =====\n" \
		"$rc" "$remotemachine"

	return $rc
}

##### Execute on this machine ################################################
function backup_local {
	[ "$#" -lt 6 ] && return 1

	local bck_type="$1"
	local bck_src="$2"
	local bck_dst="$3"
	local bck_src_secret="$4"
	local bck_dst_secret="$5"
	local bck_histdate="$6"
	shift 6

	local bck_local_prm=()
	local bck_dst_full

	bck_local_prm+=( "$@" )
	shift $#

	if [ ! -z "$bck_histdate" ] ; then # History mode
		# bck_dst_full="$bck_dst/$bck_histdate.in-progress"
		bck_dst_full=$(backup_inithist "$bck_dst" "$bck_histdate" ) || return 1
	else
		bck_dst_full="$bck_dst"
	fi

	# Interface to type_specific drivers:
	#	backup2_<type>	function name
	#	bck_src		Source URL
	#	bck_dst		Destination URL
	#	bck_src_secret	Source Secret Filename
	#	bck_dst_secret	Destination Secret Filename
	#	[ ...]		type specific futher options
	backup2_$bck_type \
		"$bck_src" \
		"$bck_dst_full" \
		"$bck_src_secret" \
		"$bck_dst_secret" \
		"${bck_local_prm[@]}" \
		|| return 1

	if [ ! -z "$bck_histdate" ] && [ "$bck_dst_full" != "$bck_dst/$bck_histdate" ] ; then
		# History mode and we used a temporary dir for backup (.in-progress)
		mv "$bck_dst_full" "$bck_dst/$bck_histdate" || return 1
		printf "Backup in history mode successful - renamed to %s\n" \
			"$bck_dst/$bck_histdate" >&2
	fi

	return 0
}

##### Notify on Backup result and Deleted files via Email ####################
function backup_notify {
	# Options:
	#	--deleted List deleted files on remote system
	# Parms
	# 	1 - Sender Email adress, e.g. "my name <no-reply@example.org"
	#	2 - Recipient Email adress

	return 0
	# Old implementation as base follow
	###################################

	#if [ -s $LDIR/crypt.filestodelete ] ; then
	#printf "Sending EMail with list of deleted files.\n"
	#(
	#    printf "%s finished at %s\n\n" "$0" "$(date +"%Y-%m-%d %H:%M:%S")"
	#
	#    backup_rsync_print \
	#        $LDIR/crypt.filestodelete \
	#        "/srv/backup/data.crypt" \
	#        "remotebackup@stevro.dyndns.eu:/crypt"
	#
	#) 2>&1 </dev/null | mail \
	#    -r "nafets-backup-upload <no-reply@nafets.dyndns.eu>" \
	#    -s "Deleted files found" \
	#    infos@nafets.de
	#
	#else
	#    printf "No deleted Files. Not sending EMail.\n"
	#fi
	#
	#if [ -s $LDIR/euserv.fotos.filestodelete ] ||
	#   [ -s $LDIR/euserv.music.filestodelete ] ; then
	#printf "Sending EMail with list of deleted files.\n"
	#(
	#    printf "%s finished at %s\n\n" "$0" "$(date +"%Y-%m-%d %H:%M:%S")"
	#
	#    backup_rsync_print \
	#        $LDIR/euserv.fotos.filestodelete \
	#        "/srv/samba/data/fotos" \
	#        "remotebackup@stevro.dyndns.eu:/fotos"
	#
	#    backup_rsync_print \
	#        $LDIR/euserv.music.filestodelete \
	#        "/srv/samba/data/music" \
	#        "remotebackup@stevro.dyndns.eu:/music"
	#
	#) 2>&1 </dev/null | mail \
	#    -S smtp=smtp://mail.intranet.nafets.de \
	#    -S hostname=$HOSTNAME.dom.nafets.de \
	#    -r "nafets-backup-upload-euserv <no-reply@nafets.dyndns.eu>" \
	#    -s "Deleted files found" \
	#    infos@nafets.de
	#
	#else
	#    printf "No deleted Files. Not sending EMail.\n"
	#fi
	#}
}

#### Helper: Check that runon is empty else print error ######################
function check_runon_empty {
	local bck_runon="$1"
	if [ ! -z "$bck_runon" ] ; then
		printf "Parm Conflict: More than one of %s\n" \
			"--runonsrc --runondst --local"
		return 1
	else
		return 0
	fi
}

##### Helper: Check that parm#2 is not empty #################################
function check_another_parm {
	local parms="$1"
	local parm1="$2"

	if [ "$parms" -lt 2 ] ; then
		printf "Error: parameter %s needs a value\n" \
			"$parm1"
		return 1
	else
		return 0
	fi
}

##### determine where to run if user did not specify #########################
function backup_default_runon {
	[ "$#" -lt 3 ] && return 1
	local bck_type="$1"
	local bck_dst="$2"
	local bck_src="$3"
	local bck_runon=""

	if [ "$bck_type" != file ] ; then
		bck_runon=1 # can only run on destination
	else
		if   [[ "$bck_dst" == *":"* ]] &&
		     [[ "$bck_src" == *":"* ]] ; then
			printf "Error: Missing option --runonsrc or --runondst %s\n" \
				"when copying from remote to remote" >&2
			return 1
		elif [[ "$bck_dst" != *":"* ]] &&
		     [[ "$bck_src" != *":"* ]] ; then
			bck_runon=0
		elif [[ "$bck_src" != *":"* ]] ; then
			bck_runon=-1
		elif [[ "$bck_dst" != *":"* ]] ; then
			bck_runon=1
		else
			prinf "Internal Error at %s.\n" \
				"autodetecting runon" >&2
			return 99
		fi
	fi

	printf "%s\n" "$bck_runon"
	return 0
}

##### backup - entry point for custom script #################################
# backup <type> <source> <dest> [ global-options ] [ -- ] [ type-options ]
function backup {
	# This function is called by the custom script.

	#----- Parameter handling --------------------------------------------
	local bck_global_prm=0
	local bck_runon=""
	local bck_local_prm=()
	local bck_histdate=""
	while [ $# -gt 0 ] ; do
		if [ "$1" == "--runonsrc" ] ; then # Execute on source
			check_runon_empty "$bck_runon" || return 1
			bck_runon=-1
			shift
		elif [ "$1" == "--runondst" ] ; then # Execute on destination
			check_runon_empty "$bck_runon" || return 1
			bck_runon=1
			shift
		elif [ "$1" == "--local" ] ; then # Run locally only
			check_runon_empty "$bck_runon" || return 1
			bck_runon=0
			shift
		elif [ "$1" == "--hist" ] ; then # Backup in history mode
			bck_histdate="$(date +%Y/%m/%d)" || return 1
			shift
		elif [ "$1" == "--histdate" ] ; then
			check_another_parm "$#" "$1" || return 1
			bck_histdate="$(date +%Y/%m/%d "--date=$2")" || return 1
			shift 2
		elif [ "$1" == "--histraw" ] ; then
			check_another_parm "$#" "$1" || return 1
			bck_histdate="$2"
			shift 2
		elif [ "$1" == "--srcsecret" ] ; then
			check_another_parm "$#" "$1" || return 1
			bck_src_secret="$2"
			shift 2
		elif [ "$1" == "--dstsecret" ] ; then
			check_another_parm "$#" "$1" || return 1
			bck_dst_secret="$2"
			shift 2
		elif [ "$1" == "--" ] ; then # end of global parms
			shift # ignore parm "--"
			bck_local_prm+=( "$@" )
			shift $#
		elif [ "$bck_global_prm" == 0 ] ; then
			local bck_type="$1"
			((bck_global_prm++))
			shift
		elif [ "$bck_global_prm" == 1 ] ; then
			local bck_src="$1"
			((bck_global_prm++))
			shift
		elif [ "$bck_global_prm" == 2 ] ; then
			local bck_dst="$1"
			((bck_global_prm++))
			shift
		else # unknown parm -> probably type-specific
			bck_local_prm+=( "$1" )
			shift
		fi
	done

	#----- Validations ---------------------------------------------------
	if [ "$bck_global_prm" != 3 ] ; then
		printf "%s %s :\n\t%s\n\t---%s %s %s\n" \
			"Error in custom config script" \
			"when calling backup with parms" \
			"$*" \
			"Missing non-option parms" \
			"(type, source, dest) - got "
			"$bck_global_prm"
		NAFETS227BACKUP_GRC=1
		return 1
	elif [ ! -z "$bck_src_secret" ] && [ ! -f "$bck_src_secret" ] ; then
		printf "Error: Source Secret File %s not found.\n" \
			"$bck_src_secret"
		return 1
	elif [ ! -z "$bck_tgt_secret" ] && [ ! -f "$bck_tgt_secret" ] ; then
		printf "Error: Target Secret File %s not found.\n" \
			"$bck_tgt_secret"
		return 1
	elif	[ ! -z "$bck_histdate" ] && 
			[[ ! "$bck_histdate" =~ [0-9]{4}/[0-9]{2}/[0-9]{2} ]] ; then
		printf "Error: Invalid format %s in --hist* (not YYYY/MM/DD).\n" \
			"$bck_histdate"
		return 1
	elif [ "$bck_type" == imap ] ; then
		:
	elif [ "$bck_type" == file ] ; then
		:
#	elif [ "$bck_type" != mysql-kube ] &&
#	elif [ "$bck_type" != notify ] &&
	else
		printf "Wrong backup type %s " "$type"
		printf "when calling backup with\n\t%s\n" \
			"$*"
		NAFETS227BACKUP_GRC=1
		return 1
	fi

	#----- Autodetect where to run ---------------------------------------
	if [ -z "$bck_runon" ] ; then
		bck_runon=$(backup_default_runon $bck_type $bck_dst $bck_src)
		if [ "$?" != "0" ] ; then
			NAFETS227BACKUP_GRC=1
			return 1
		fi
	fi

	#----- Validation 2 after runon detection ----------------------------
	if [ "$bck_type" != file ] &&
	   [ "$bck_runon" == -1 ] ; then
		printf "Error: cannot run on source with type %s\n" \
			"$bck_type"
		NAFETS227BACKUP_GRC=1
		return 1
	fi

	#----- Execute on source, local or dest ------------------------------
	if [ "$bck_runon" == "-1" ] ; then
		if [[ "$bck_src" != *":"* ]] ; then
			backup_local \
				"$bck_type" \
				"$bck_src" \
				"$bck_dst" \
				"$bck_src_secret" \
				"$bck_dst_secret" \
				"$bck_histdate" \
				"${bck_local_prm[@]}"
			rc=$?
		else
			backup_remote \
				"${bck_src%%:*}" \
				"$bck_src_secret" \
				"$bck_type" \
				"$bck_src" \
				"$bck_dst" \
				"" \
				"$bck_dst_secret" \
				"$bck_histdate" \
				"${bck_local_prm[@]}"
			rc=$?
		fi
	elif [ "$bck_runon" == "0" ] ; then
			backup_local \
				"$bck_type" \
				"$bck_src" \
				"$bck_dst" \
				"$bck_src_secret" \
				"$bck_dst_secret" \
				"$bck_histdate" \
				"${bck_local_prm[@]}"
			rc=$?
	elif [ "$bck_runon" == "1" ] ; then
		if [[ "$bck_dst" != *":"* ]] ; then
			backup_local \
				"$bck_type" \
				"$bck_src" \
				"$bck_dst" \
				"$bck_src_secret" \
				"$bck_dst_secret" \
				"$bck_histdate" \
				"${bck_local_prm[@]}"
			rc=$?
		else
			backup_remote \
				"${bck_dst%%:*}" \
				"$bck_dst_secret" \
				"$bck_type" \
				"$bck_src" \
				"$bck_dst" \
				"$bck_src_secret" \
				"" \
				"$bck_histdate" \
				"${bck_local_prm[@]}"
			rc=$?
		fi
	else
		printf "Internal Error at %s.\n" \
			"starting execution"
		NAFETS227BACKUP_GRC=1
		return 99
	fi

	#----- Error handling and return -------------------------------------
	if [ $rc -ne 0 ] ; then
		NAFETS227BACKUP_GRC=1
		return 1
	fi

	return 0
}

##### Main ###################################################################
printf "starting ENTRYPOINT backup_main\n"
readonly REMOTE_MODDIR=/usr/local/lib/nafets227.backup

##### Parse Configs / Envirionment ###########################################
DEBUG=${DEBUG-0}
debug=$DEBUG

##### Ensure running on bash v4+ #############################################
if [[ ${BASH_VERSION:0:1} -lt "4" ]] ; then
	# Special workaround for MacOS:
	# system bash in /bin/bash is V3
	# but v4+ max be available in /usr/local/bin
	if [[ -x /usr/local/bin/bash ]] &&
	   bashver=$(/usr/local/bin/bash -c 'echo $BASH_VERSION') &&
	   [[ ${bashver:0:1} -ge 4 ]]
	then
		PATH="/usr/local/bin:$PATH" /usr/local/bin/bash "$0" "$@"
		exit $?
	else
		printf "bash version below 4: %s\n" "$BASH_VERSION"
		exit 1
	fi
elif ! which true >/dev/null || ! which false >/dev/null ; then
	printf "true or false not found in path.\n"
	exit 1
fi

#Source all modules in install.d
for f in $(dirname $0)/*.sh ; do
    echo "Loading Module $f"
    . $f
    if [ x$? != x0 ] ; then
	    printf "Error loading module %s\n" "$f"
	    exit 1
    fi
done

if [ x"$DEBUG" == x1 ] ; then
	set -x
fi

NAFETS227BACKUP_GRC=0
##### Now start the custom scipt
if [ $# == 0 ] ; then
	printf "No command given.\n"
	exit 1
fi

printf "executing custom command %s\n" "$*"
"$@" || NAFETS227BACKUP_GRC=3

if [ "x$NAFETS227BACKUP_GRC" == "x0" ] ; then
	printf "Success: all Backup Tasks have been completed successfully.\n"
	exit 0
else
	printf "Error %d: " "$NAFETS227BACKUP_GRC"
	printf "not all Backup Tasks have been completed successfully.\n"
	exit 1
fi
