#!/bin/sh
#
# Backup Files
#
# (C) 2013 Stefan Schallenberg
#

##### backup2_imap ###########################################################
function backup2_imap {
        if [ "$#" -ne 4 ] ; then
                printf "Error in custom config script. "
                printf "Calling backup imap with parms:\n\t%s\n"
                        "$*"
                return 1
	elif [ x"$DEBUG" == x1 ] ; then
		printf "DEBUG: %s %s\n" "$FUNCNAME" "$*"
	fi

        local bckimap_src="$1"
        local bckimap_dst="$2"
        local bckimap_srv="$3"
        local bckimap_pw="$4"

	local emailuser="${bckimap_src%%@*}"
	local emailuser="${emailuser,,}" # convert to lowercase
	local bckimap_dst_server="${3%%:*}"
	local bckimap_dst_port=${3:$((${#bckimap_dst_server} + 1))}

	if [ -z "$bckimap_dst_port" ] ; then
		printf "Error: IMAP Port not specified in URL %s.\n" \
			"bckimap_srv"
		return 1
	fi

	local ssl=""
	if [ "$bckimap_dst_port" == "143" ] ; then
		ssl=$'ssl = no\nstarttls = yes'
	else
		ssl=$'ssl = yes'
	fi

	if [ ! -d "$bckimap_dst" ] ; then
		mkdir -p "$bckimap_dst" || return 1
	fi

	offlineimap -c /dev/fd/10 10<<-EOFCFG 11<<-EOFPW || return 1
		# OfflineIMAP configuration
		#
		# (C) 2012-2015 Stefan Schallenberg
		# Generated by ${BASH_SOURCE##*/}

		[general]
		accounts = $emailuser
		metadata = $bckimap_dst/.offlineimap

		[Account $emailuser]
		localrepository = ${emailuser}Local
		remoterepository = ${emailuser}Remote

		[Repository ${emailuser}Local]
		type = Maildir
		localfolders = $bckimap_dst

		[Repository ${emailuser}Remote]
		type = IMAP
		readonly = True
		remotehost = $bckimap_dst_server
		remoteport = $bckimap_dst_port
		remoteuser = $bckimap_src
		remotepassfile = /dev/fd/11
		subscribedonly = no

		$ssl
		EOFCFG
		$bckimap_pw
		EOFPW

	return 0
}

