---
name: Docker-ci

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

permissions:
  contents: read

env:
  VERSION: 0.0.0 # dummy value will be replaced by calculate version step
  ISLATEST: ${{ github.ref_type == 'tag' || github.event_name == 'schedule' }}
  IMGNAME: ${{ github.event.repository.name }}
  CHARTNAME: ${{ github.repository_owner }}-${{ github.event.repository.name }}

jobs:
  # Lint and build intentionally run in parallel. A failed lint may waste
  # some build time, but a successful build does not have to wait for lint.

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false
      - name: Calculate version
        id: version
        run: |
          set -Eeuo pipefail ${{ runner.debug && '-x' || '' }}
          shopt -s inherit_errexit
          . scripts/get-version
          # writes VERSION=1.2.3 to $GITHUB_ENV
          # writes version=1.2.3 to $GITHUB_OUTPUT
      - name: Update Helm chart
        run: |
          yq -i \
            '.version="${{ env.VERSION }}"' \
            "charts/$CHARTNAME/Chart.yaml"
          yq -i \
            '.appVersion="${{ env.VERSION }}"' \
            "charts/$CHARTNAME/Chart.yaml"
      - name: Lint helm and render examples/tests
        run: scripts/helm-lint-render
      - name: Load super-linter configuration
        # Use grep inverse matching to exclude eventual comments in the .env
        # file because the GitHub Actions command to set environment variables
        # doesn't support comments. Ref:
        # editorconfig-checker-disable-next-line
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable
        run: grep -v '^#' .github/linters/super-linter.env >> "$GITHUB_ENV"
      - name: SuperLint
        uses: super-linter/super-linter/slim@v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.version.outputs.version }}
      #editorconfig-checker-disable
      image: >-
        ghcr.io/${{ github.repository_owner }}/${{ env.IMGNAME }}:${{ steps.version.outputs.version }}
      #editorconfig-checker-enable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Calculate version
        id: version
        run: |
          set -Eeuo pipefail ${{ runner.debug && '-x' || '' }}
          shopt -s inherit_errexit
          . scripts/get-version
          # writes VERSION=1.2.3 to $GITHUB_ENV
          # writes version=1.2.3 to $GITHUB_OUTPUT
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMGNAME }}
          tags: |
            type=raw,value=${{ env.VERSION }}
      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha
          outputs: type=docker,dest=dist/${{ env.IMGNAME }}.image.tar
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}

      - name: Upload Docker image
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.IMGNAME }}.image.tar
          path: dist/${{ env.IMGNAME }}.image.tar
          retention-days: 1
      - name: Update Helm chart
        if: env.CHARTNAME != ''
        run: |
          # jscpd:ignore-start intentionally copied from job lint
          yq -i \
            '.version="${{ env.VERSION }}"' \
            "charts/$CHARTNAME/Chart.yaml"
          yq -i \
            '.appVersion="${{ env.VERSION }}"' \
            "charts/$CHARTNAME/Chart.yaml"
          # jscpd:ignore-end
      - name: Package Helm
        if: env.CHARTNAME != ''
        run: |
          helm dependency update charts/nafets227-backup
          helm package "charts/$CHARTNAME" --destination dist
      - name: Upload Helm chart
        if: env.CHARTNAME != ''
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.CHARTNAME }}-${{ env.VERSION }}.tgz
          path: dist/${{ env.CHARTNAME }}-${{ env.VERSION }}.tgz
          retention-days: 1

  test-base-imap:
    needs: build
    runs-on: ubuntu-latest
    # Avoid running multiple test steps in parallel that would interfere with
    # each other since they use the same test Email and OneDrive.
    concurrency:
      group: ci-test-base-imap
      queue: max
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt install s-nail offlineimap
      - name: Download Docker image
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.IMGNAME }}.image.tar
          path: dist
      - name: Load Docker image
        run: docker load --input "dist/$IMGNAME.image.tar"
      - name: Test
        env:
          GH_TOKEN: ${{ secrets.GH_SECRET_ADMIN_TOKEN }}
          MAIL_PW: ${{ secrets.MAIL_PW }}
          IMAGE: ${{ needs.build.outputs.image }}
        run: |
          set -Eeuo pipefail ${{ runner.debug && '-x' || '' }}
          shopt -s inherit_errexit

          cat >tests/mail.password <<<"$MAIL_PW"
          unset MAIL_PW

          sudo bash -c 'ssh-keygen -N "" -f ~/.ssh/id_ed25519'
          sudo bash -c 'cat ~/.ssh/id_ed25519.pub >>~/.ssh/authorized_keys'
          sudo bash -c 'touch ~/.hushlogin'

          sudo bash ${{ runner.debug && '-x' || '' }} \
            tests/run-tests all '!rclone' '!file' "$IMAGE"

          rm tests/mail.password

  # jscpd:ignore-start
  test-rclone:
    needs: build
    runs-on: ubuntu-latest
    # Avoid running multiple test steps in parallel that would interfere with
    # each other since they use the same test Email and OneDrive.
    concurrency:
      group: ci-test-rclone
      queue: max
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt install rclone
      - name: Download Docker image
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.IMGNAME }}.image.tar
          path: dist
      - name: Load Docker image
        run: docker load --input "dist/$IMGNAME.image.tar"
      - name: Test
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          GH_TOKEN: ${{ secrets.GH_SECRET_ADMIN_TOKEN }}
          IMAGE: ${{ needs.build.outputs.image }}
        run: |
          set -Eeuo pipefail ${{ runner.debug && '-x' || '' }}
          shopt -s inherit_errexit

          cat >tests/rclone.conf <<<"$RCLONE_CONF"
          unset RCLONE_CONF

          sudo bash -c 'ssh-keygen -N "" -f ~/.ssh/id_ed25519'
          sudo bash -c 'cat ~/.ssh/id_ed25519.pub >>~/.ssh/authorized_keys'
          sudo bash -c 'touch ~/.hushlogin'

          sudo bash ${{ runner.debug && '-x' || '' }} \
            tests/run-tests rclone "$IMAGE"

          gh secret set RCLONE_CONF < tests/rclone.conf
          rm tests/rclone.conf

  test-file:
    needs: build
    runs-on: ubuntu-latest
    # Avoid running multiple test steps in parallel that would interfere with
    # each other since they use the same test Email and OneDrive.
    concurrency:
      group: ci-test-file
      queue: max
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false
      - name: Download Docker image
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.IMGNAME }}.image.tar
          path: dist
      - name: Load Docker image
        run: docker load --input "dist/$IMGNAME.image.tar"
      - name: Test
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          IMAGE: ${{ needs.build.outputs.image }}
        run: |
          set -Eeuo pipefail ${{ runner.debug && '-x' || '' }}
          shopt -s inherit_errexit

          sudo bash -c 'ssh-keygen -N "" -f ~/.ssh/id_ed25519'
          sudo bash -c 'cat ~/.ssh/id_ed25519.pub >>~/.ssh/authorized_keys'
          sudo bash -c 'touch ~/.hushlogin'

          sudo bash ${{ runner.debug && '-x' || '' }} \
            tests/run-tests file "$IMAGE"
    # jscpd:ignore-end

  push:
    needs:
      - lint
      - build
      - test-base-imap
      - test-rclone
      - test-file
    env:
      VERSION: ${{ needs.build.outputs.version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # jscpd:ignore-start
      - name: Download Docker image
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.IMGNAME }}.image.tar
          path: dist
      - name: Load Docker image
        run: docker load --input "dist/$IMGNAME.image.tar"
      - name: Download Helm chart
        if: env.CHARTNAME != ''
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.CHARTNAME }}-${{ env.VERSION }}.tgz
          path: dist
      # jscpd:ignore-end
      - name: Log into registry ghcr.io
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        env:
          REFTYPE: ${{ github.ref_type }}
          IMG: ghcr.io/${{ github.repository_owner }}/${{ env.IMGNAME }}
        run: |
          docker push "$IMG:$VERSION"

          if [[ "$ISLATEST" == "true" ]]; then
            docker tag "$IMG:${VERSION}" "$IMG:latest"
            docker push "$IMG:latest"
          fi

          # make sure additional tags works
          docker tag "$IMG:${VERSION}" "$IMG:latestdummycitest"
          docker push "$IMG:latestdummycitest"
      - name: Push Helm chart
        if: env.CHARTNAME != ''
        run: |
          helm push \
            "dist/$CHARTNAME-$VERSION.tgz" \
            "oci://ghcr.io/${{ github.repository_owner }}/charts"

  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Cleanup old Docker images
        if: github.event_name != 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEEP_DAYS: 30
        run: |
          scripts/cleanup-ghcr "$IMGNAME"
      - name: Cleanup old Helm charts
        if: github.event_name != 'pull_request' && env.CHARTNAME != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEEP_DAYS: 30
        run: |
          scripts/cleanup-ghcr "charts/$CHARTNAME"
