---
name: Docker-ci

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

permissions:
  contents: read

# avoid to run multiple jobs in parallel that would interfere with each other
# in the test step, since they would use the same test Email and OneDrive.
concurrency: ci

env:
  VERSION: 0.0.0 # dummy value will be replaced by calculate version step

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false

      - name: Calculate version
        id: version
        run: |
          set -Eeuo pipefail ${{ runner.debug && '-x' || '' }}
          shopt -s inherit_errexit
          . scripts/get-version
          # writes VERSION=1.2.3 to $GITHUB_ENV

      - name: Update Helm chart
        run: |
          yq -i \
            '.version="${{ env.VERSION }}"' \
            charts/nafets227-backup/Chart.yaml
          yq -i \
            '.appVersion="${{ env.VERSION }}"' \
            charts/nafets227-backup/Chart.yaml

      - name: Lint helm and render examples/tests
        run: scripts/helm-lint-render

      - name: Load super-linter configuration
        # Use grep inverse matching to exclude eventual comments in the .env
        # file because the GitHub Actions command to set environment variables
        # doesn't support comments.
        # editorconfig-checker-disable-next-line
        # Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable
        run: grep -v '^#' .github/linters/super-linter.env >> "$GITHUB_ENV"

      - name: SuperLint
        uses: super-linter/super-linter/slim@v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log into registry ghcr.io
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate version
        id: version
        run: |
          set -Eeuo pipefail ${{ runner.debug && '-x' || '' }}
          shopt -s inherit_errexit
          . scripts/get-version
          # writes VERSION=1.2.3 to $GITHUB_ENV

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ env.VERSION }}

            # latest only for Release Tags
            type=raw,value=latest,enable=${{ github.ref_type == 'tag' }}

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Helm chart
        run: |
          yq -i \
            '.version="${{ env.VERSION }}"' \
            charts/nafets227-backup/Chart.yaml
          yq -i \
            '.appVersion="${{ env.VERSION }}"' \
            charts/nafets227-backup/Chart.yaml

      - name: Package Helm
        run: |
          helm dependency update charts/nafets227-backup
          helm package charts/nafets227-backup --destination dist

      - name: setup
        id: setup
        run: |
          sudo apt install s-nail rclone offlineimap

      - name: test
        id: test
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
          GH_TOKEN: ${{ secrets.GH_SECRET_ADMIN_TOKEN }}
          MAIL_PW: ${{ secrets.MAIL_PW }}
        run: |
          set -Eeuo pipefail ${{ runner.debug && '-x' || '' }}
          shopt -s inherit_errexit

          cat >tests/rclone.conf <<<"$RCLONE_CONF"
          cat >tests/mail.password <<<"$MAIL_PW"
          unset RCLONE_CONF MAIL_PW

          sudo bash -c 'ssh-keygen -N "" -f ~/.ssh/id_rsa'
          sudo bash -c 'cat ~/.ssh/id_rsa.pub >>~/.ssh/authorized_keys'
          sudo bash -c 'touch ~/.hushlogin'

          sudo bash ${{ runner.debug && '-x' || '' }} tests/run-tests

          gh secret set RCLONE_CONF < tests/rclone.conf
          rm tests/rclone.conf tests/mail.password

      - name: Push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push Helm chart
        run: |
          helm push \
            dist/nafets227-backup-${{ env.VERSION }}.tgz \
            oci://ghcr.io/${{ github.repository_owner }}/charts

      - name: Cleanup old Docker images
        if: github.event_name != 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEEP_DAYS: 30
        run: |
          scripts/cleanup-ghcr backup

      - name: Cleanup old Helm charts
        if: github.event_name != 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEEP_DAYS: 30
        run: |
          scripts/cleanup-ghcr charts/nafets227-backup
